// FUNCTION CLASSIFICATION
// 1. NO AGRUMEN WITHOUT RETURN TYPE 
// 2. NO ARGUMENT WITH RETURN TYPE 
// 3. WITH ARGUMENT WITHOUT RETURN TYPE 
// 4. WITH ARGUMENT WITH RETURN TYPE 

// NO AGRUMEN WITHOUT RETURN TYPE 
